services:
  # Service for the Next.js application using an ECR image
  next-app:
    build:
      # Reference ECR image
      image: 842080455908.dkr.ecr.us-east-1.amazonaws.com/jackw/next-app:latest
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    environment:
      - NODE_ENV=production  # Set environment variable for production
    networks:
      - personality-lab-network  # Connect to the custom personality-lab-network

  # Service for the WebSocket server using an ECR image
  u-websocket:
    build:
      # Reference ECR image
      image: 842080455908.dkr.ecr.us-east-1.amazonaws.com/u-websocket:latest
    ports:
      - "3001:3001"  # Map port 3001 on the host to port 3001 in the container
    environment:
      - NODE_ENV=production  # Set environment variable for production
    # volumes:
    #   - /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/canpersonalitychange.com/canpersonalitychange.com.crt:/etc/ssl/certs/canpersonalitychange.com.crt:ro
    #   - /var/lib/caddy/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/canpersonalitychange.com/canpersonalitychange.com.key:/etc/ssl/private/canpersonalitychange.com.key:ro
    networks:
      - personality-lab-network  # Connect to the custom personality-lab-network
    depends_on:
      - next-app  # Start this service after next-app is started


networks:
  personality-lab-network:
    driver: bridge  # Use the default bridge network driver
