export const GENDER_AND_CREATIVITY_FRAGMENT_ID_PREFACE = `gender-and-creativity-us`


export const questionBankLegend = [
  `Strongly Disagree`,
  `Disagree`,
  `Neutral`,
  `Agree`,
  `Strongly Agree`,
]


export const questionBank = {
  spendTimeWithOthers: [
    `Is outgoing, sociable`,
    `Is compassionate, has a soft heart`,
    `Tends to be disorganized`,
    `Is relaxed, handles stress well`,
    `Has few artistic interests`,
    `Has an assertive personality`,
    `Is respectful, treats others with respect`,
    `Tends to be lazy`,
    `Stays optimistic after experiencing a setback`,
    `Is curious about many different things`,
    `Rarely feels excited or eager`,
    `Tends to find fault with others`,
    `Is dependable, steady`,
    `Is moody, has up and down mood swings`,
    `Is inventive, finds clever ways to do things`,
    `Tends to be quiet`,
    `Feels little sympathy for others`,
    `Is systematic, likes to keep things in order`,
    `Can be tense`,
    `Is fascinated by art, music, or literature`,
    `Is dominant, acts as a leader`,
    `Starts arguments with others`,
    `Has difficulty getting started on tasks`,
    `Feels secure, comfortable with self`,
    `Avoids intellectual, philosophical discussions`,
    `Is less active than other people`,
    `Has a forgiving nature`,
    `Can be somewhat careless`,
    `Is emotionally stable, not easily upset`,
    `Has little creativity`,
    `Please, select 'neutral' for this option`,
    `Is sometimes shy, introverted`,
    `Is helpful and unselfish with others`,
    `Keeps things neat and tidy`,
    `Worries a lot`,
    `Values art and beauty`,
    `Finds it hard to influence people`,
    `Is sometimes rude to others`,
    `Is efficient, gets things done`,
    `Often feels sad`,
    `Is complex, a deep thinker`,
    `Is full of energy`,
    `Is suspicious of others' intentions`,
    `Is reliable, can always be counted on`,
    `Keeps their emotions under control`,
    `Has difficulty imagining things`,
    `Is talkative`,
    `Can be cold and uncaring`,
    `Leaves a mess, doesn't clean up`,
    `Rarely feels anxious or afraid`,
    `Thinks poetry and plays are boring`,
    `Prefers to have others take charge`,
    `Is polite, courteous to others`,
    `Is persistent, works until the task is finished`,
    `Tends to feel depressed, blue`,
    `Has little interest in abstract ideas`,
    `Shows a lot of enthusiasm`,
    `Assumes the best about people`,
    `Sometimes behaves irresponsibly`,
    `Is temperamental, gets emotional easily`,
    `Is original, comes up with new ideas`
  ],
  levelOfAgreement: [
    `It's not wise to tell your secrets`,
    `I like to use clever manipulation to get my way`,
    `Whatever it takes, you must get the important people on your side`,
    `Avoid direct conflict with others because they may be useful in the future`,
    `It's wise to keep track of information that you can use against people later`,
    `You should wait for the right time to get back at people`,
    `There are things you should hide from other people to preserve your reputation`,
    `Make sure your plans benefit yourself, not others`,
    `Most people can be manipulated`,
    `People see me as a natural leader`,
    `I hate being the center of attention`,
    `Many group activities tend to be dull without me`,
    `Please, select 'agree' for this option`,
    `I know that I am special because everyone keeps telling me so`,
    `I like to get acquainted with important people`,
    `I feel embarrassed if someone compliments me`,
    `I have been compared to famous people`,
    `I am an average person`,
    `I insist on getting the respect I deserve`,
    `I like to get revenge on authorities`,
    `I avoid dangerous situations`,
    `Payback needs to be quick and nasty`,
    `People often say I'm out of control`,
    `It's true that I can be mean to others`,
    `People who mess with me always regret it`,
    `I have never gotten into trouble with the law`,
    `I enjoy having sex with people I hardly know`,
    `I'll say anything to get what I want`
  ]
}

