name: Docker Image CI

on:
  push:
    branches: [ "main", "feat/dynamodb" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 1. Login to Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: 2. Build the Docker image
      run: docker build -t personality-lab-app .
    - name: 3. Tag newly built image
      run: docker tag personality-lab-app platocrat/personality-lab-app
    - name: 4. Push Docker image to private repository
      run: docker push platocrat/personality-lab-app

    
