name: Prepare Docker Image for EC2

env:
  SSH_KEY: ${{ secrets.SSH_KEY }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_HOSTNAME: ${{ secrets.EC2_HOSTNAME }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

on:
  push:
    branches: [ "main", "feat/dynamodb" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
      # Phase 1: Build and Push Docker Image to Docker Hub Repository
      - name: 1. Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN
      - name: 2. Build the Docker image
        run: docker build -t personality-lab-app .
      - name: 3. Tag newly built image
        run: docker tag personality-lab-app $DOCKER_HUB_REPOSITORY
      - name: 4. Push Docker image to private repository
        run: docker push $DOCKER_HUB_REPOSITORY
      # Phase 2: Pull Docker image on EC2 instance and start NextJS app
      - name: 5. Create SSH key
        run: echo "$SSH_KEY" > ssh_key && chmod 600 ssh_key
      - name: 6. SSH into EC2 instance, prune Docker system data, and pull Docker image
        # sudo docker system prune -a -f && # No longer compatible with older Docker version
        run: ssh -o StrictHostKeyChecking=no -i ssh_key $EC2_USERNAME@$EC2_HOSTNAME '
          sudo docker pull platocrat/personality-lab-app
          '